FORMAT: 1A

# Student Review System

The Student Review System is a web application for peer review and self-evaluation, designed for schools and universities.

This is the documentation for the Student Review System API. This API is designed to be used in the client application being built as a part of this project.

## Users Collection [/users]

### List All Users [GET]

+ Request
    + Headers  
    
            Authorization: Bearer validJsonWebToken

+ Response 200 (application/json)

        {
            success: true,
            users: [
                {
                    "email": "bob@example.com",
                    "name": "Bob Jones",
                    "isAdmin": false
                }  
            ]
        }
            
+ Request
    + Headers  
    
            Authorization: Bearer invalidJsonWebToken
        
+ Response 401 (application/json)

        {
            success: false,
            message: "User is not authorized"
        }