version: '2'

services:
  api:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - "mongo:mongo"
  mongo:
    image: mongo:latest